# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20171111_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='note_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
